### ISSUE TITLE
TS Roles / Connectivity Issue

### ISSUE THREAD

**Issue by dstevens79** [warlof/seat-teamspeak#17]
Hello and thank you for your efforts on this epic plugin.

i am currently using ts connector 3.0.8 on seat api 3.0.5 and teamspeak 3.5.0 
users can join servers properly. 
but i have the following likely not working as intended issues : 

1  No TS roles are ever displayed under access management
2  The find you and register button returns : 
An unhandled error occurred. Please contact your administrator.
3 user mapping shows no data available in the table.

I am 100% sure my server is whitelisted and i dont think its a port issue because have tried this on the same server as the host on one attempt and on another remote server ip address. Ports are not blocked because i have a bot that runs on ts doing various duties (this is also how i know my serveradmin pw works properly)

i have followed the setup instructions line for line twice.
seat itself is setup and working 100% as intended.
plz help.

Thank you again.

**Comment by warlof** [comment]
Hi,

Regarding your first problem, did you click on the button `Update TeamSpeak Server Group` into the settings page?

Regarding the seconds problem, can you check into your logs? Especially `laravel-{date}.log` which is located into your SeAT installation, storages folder, logs subfolders.

**Comment by dstevens79** [comment]
hello, thank you for a quick response, 

this is the block i think your after from that log : 


```
[2018-12-19 00:00:23] local.WARNING: Warlof\Seat\Connector\Teamspeak\Jobs\TeamspeakGroupsUpdate - An other job is already queued  
[2018-12-19 00:00:42] local.DEBUG: Structure resolver {"location_ids":[1026941704533]} 
[2018-12-19 00:01:06] local.WARNING: Warlof\Seat\Connector\Teamspeak\Jobs\TeamspeakGroupsUpdate - An other job is already queued  
[2018-12-19 00:01:13] local.DEBUG: Structure resolver {"location_ids":[]} 
[2018-12-19 00:02:03] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c198a7b976066.19685903  
[2018-12-19 00:02:03] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c198a7b9964c1.98132970  
[2018-12-19 00:02:03] local.ERROR: php_network_getaddresses: getaddrinfo failed: Name or service not known {"exception":"[object] (TeamSpeak3_Transport_Exception(code: 0): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Transport/TCP.php:55)
[stacktrace]
#0 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Transport/TCP.php(141): TeamSpeak3_Transport_TCP->connect()
#1 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine()
#2 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn()
#3 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php(333): TeamSpeak3_Adapter_Abstract->__construct(Array)
#4 /var/www/seat/vendor/warlof/seat-teamspeak/src/Helpers/TeamspeakSetup.php(120): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
#5 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(101): Warlof\\Seat\\Connector\\Teamspeak\\Helpers\\TeamspeakSetup->getInstance()
#6 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(109): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->teamspeak()
#7 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(117): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->onAfterJob()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(149): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->failed(Object(TeamSpeak3_Transport_Exception))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(165): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(TeamSpeak3_Transport_Exception))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/FailingJob.php(33): Illuminate\\Queue\\Jobs\\Job->failed(Object(TeamSpeak3_Transport_Exception))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(433): Illuminate\\Queue\\FailingJob::handle('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Transport_Exception))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(419): Illuminate\\Queue\\Worker->failJob('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Transport_Exception))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1, Object(TeamSpeak3_Transport_Exception))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(324): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(TeamSpeak3_Transport_Exception))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\\Queue\\WorkerOptions))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,medium,low...')
#19 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#26 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/seat/vendor/symfony/console/Application.php(953): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 
```

**Comment by warlof** [comment]
Did you provide a domain to the teamspeak server address?
It seems your server is not able to resolve the domain into an IP address. 

You could double check dns.

**Comment by dstevens79** [comment]
hello again and merry christmas

ok so... it took me a while poking around with port settings hoping for something to fall into place.
i gave up on that and then poking around in the logs and saw this : 

```
[2018-12-23 00:01:05] local.WARNING: Warlof\Seat\Connector\Teamspeak\Jobs\TeamspeakGroupsUpdate - An other job is already queued  
[2018-12-23 00:01:13] local.DEBUG: Structure resolver {"location_ids":[1026941704533]} 
[2018-12-23 00:01:43] local.DEBUG: Structure resolver {"location_ids":[]} 
[2018-12-23 00:02:03] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c1ed07b3da4e4.10650041  
[2018-12-23 00:02:03] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c1ed07b3e4654.96996836  
[2018-12-23 00:02:03] local.ERROR: Failed to parse address "THEPASSWORD@https:" {"exception":"[object] (TeamSpeak3_Transport_Exception(code: 0): Failed to parse address \"THEPASSWORD@https:\" at /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Transport/TCP.php:55)
[stacktrace]
#0 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Transport/TCP.php(141): TeamSpeak3_Transport_TCP->connect()
#1 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine()
#2 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn()
#3 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php(333): TeamSpeak3_Adapter_Abstract->__construct(Array)
#4 /var/www/seat/vendor/warlof/seat-teamspeak/src/Helpers/TeamspeakSetup.php(120): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
#5 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(101): Warlof\\Seat\\Connector\\Teamspeak\\Helpers\\TeamspeakSetup->getInstance()
#6 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(109): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->teamspeak()
#7 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(117): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->onAfterJob()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(149): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->failed(Object(TeamSpeak3_Transport_Exception))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(165): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(TeamSpeak3_Transport_Exception))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/FailingJob.php(33): Illuminate\\Queue\\Jobs\\Job->failed(Object(TeamSpeak3_Transport_Exception))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(433): Illuminate\\Queue\\FailingJob::handle('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Transport_Exception))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(419): Illuminate\\Queue\\Worker->failJob('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Transport_Exception))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1, Object(TeamSpeak3_Transport_Exception))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(324): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(TeamSpeak3_Transport_Exception))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\\Queue\\WorkerOptions))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,medium,low...')
#19 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#26 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/seat/vendor/symfony/console/Application.php(953): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 

```
i saw \"THEPASSWORD@https:\ and decided the problem might be tied to my password somehow so i changed my password in the settings, and i peeked at the logs and i get this when i do that : 
```

[2018-12-23 09:20:13] local.WARNING: Warlof\Seat\Connector\Teamspeak\Jobs\TeamspeakGroupsUpdate - An other job is already queued  
[2018-12-23 09:20:37] local.DEBUG: Structure resolver {"location_ids":[1026941704533,1021596729153,1027088061051]} 
[2018-12-23 09:21:06] local.WARNING: Warlof\Seat\Connector\Teamspeak\Jobs\TeamspeakGroupsUpdate - An other job is already queued  
[2018-12-23 09:21:57] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c1f53b53638f5.91081822  
[2018-12-23 09:21:57] local.DEBUG: Spawning a new Warlof\Seat\Connector\Teamspeak\Helpers\TeamspeakSetup instance with UID SeAT_5c1f53b53ccde8.89364574  
[2018-12-23 09:21:57] local.ERROR: invalid loginname or password {"exception":"[object] (TeamSpeak3_Adapter_ServerQuery_Exception(code: 520): invalid loginname or password at /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:316)
[stacktrace]
#0 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php(88): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String))
#1 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery.php(140): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'login client_lo...', Object(TeamSpeak3_Node_Host), true)
#2 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Abstract.php(70): TeamSpeak3_Adapter_ServerQuery->request('login client_lo...', true)
#3 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Abstract.php(94): TeamSpeak3_Node_Abstract->request('login client_lo...')
#4 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Host.php(804): TeamSpeak3_Node_Abstract->execute('login', Array)
#5 /var/www/seat/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php(341): TeamSpeak3_Node_Host->login(Object(TeamSpeak3_Helper_String), Object(TeamSpeak3_Helper_String))
#6 /var/www/seat/vendor/warlof/seat-teamspeak/src/Helpers/TeamspeakSetup.php(120): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
#7 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(101): Warlof\\Seat\\Connector\\Teamspeak\\Helpers\\TeamspeakSetup->getInstance()
#8 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(109): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->teamspeak()
#9 /var/www/seat/vendor/warlof/seat-teamspeak/src/Jobs/TeamspeakGroupsUpdate.php(117): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->onAfterJob()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(149): Warlof\\Seat\\Connector\\Teamspeak\\Jobs\\TeamspeakGroupsUpdate->failed(Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(165): Illuminate\\Queue\\CallQueuedHandler->failed(Array, Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/FailingJob.php(33): Illuminate\\Queue\\Jobs\\Job->failed(Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(433): Illuminate\\Queue\\FailingJob::handle('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(419): Illuminate\\Queue\\Worker->failJob('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1, Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(324): Illuminate\\Queue\\Worker->handleJobException('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions), Object(TeamSpeak3_Adapter_ServerQuery_Exception))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\\Queue\\WorkerOptions))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,medium,low...')
#21 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#28 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /var/www/seat/vendor/symfony/console/Application.php(953): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 {main}
"} 
```

so it is connecting sure enough, but i dont get its issue now more than ever

it was not a port issue as i reset all my port settings back to normal before stumbling across this.

i still get the original error i posted as well
what is it looking for there?

**Comment by dstevens79** [comment]
solution : 

passwords CANNOT start with an @ sign
